name: Testes Node.js Manuais

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependências (aula6)
        run: |
          cd aula6
          npm install
      - name: Executar testes (aula6)
        run: |
          cd aula6
          npm test
      - name: Instalar dependências (exercicio-aula6)
        run: |
          cd exercicio-aula6
          npm install
      - name: Executar testes (exercicio-aula6)
        run: |
          cd exercicio-aula6
          npm test 